[project]
name = "movie-viewer"
version = "0.3.0"
description = "Watch downloaded movies and shows easly"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "colorlog>=6.10.1",
    "lxml>=6.1.1",
    "pillow>=11.2.1",
    "pyqt6>=6.9.0",
    "pyqtwaitingspinner>=1.2.6",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "selenium>=4.46.0",
]

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "ruff>=0.15.9",
]
pyinstaller = [
    "pyinstaller>=6.19.0",
]

[tool.mypy]
python_version = "3.13"
files = ["."]
explicit_package_bases = true
mypy_path = "."
exclude = [
    "^dist/",
    "^build/",
    "^\\.venv/",
    "^scripts/",
]
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
no_implicit_optional = true
show_error_codes = true
pretty = true
disable_error_code = "import-untyped"

[[tool.mypy.overrides]]
module = "pyqtwaitingspinner.*"
ignore_missing_imports = true

[tool.pyright]
reportOptionalMemberAccess = "none"
reportUnknownVariableType = "none"
reportPrivateLocalImportUsage = "none"
reportUnknownParameterType = "none"
reportMissingParameterType = "none"
reportUnknownMemberType = "none"
reportUnannotatedClassAttribute = "none"
reportUnusedCallResult = "none"
reportUnknownArgumentType = "none"
reportAny = "none"
reportImplicitOverride = "none"
reportMissingTypeArgument = "none"
reportUnknownLambdaType = "none"
reportUninitializedInstanceVariable = "none"
reportExplicitAny = "none"
reportIncompatibleMethodOverride = "none"
reportMatchNotExhaustive = "none"
reportPrivateUsage = "none"
reportUnnecessaryTypeIgnoreComment = "none"
reportMissingTypeStubs = "none"
reportReturnType = "warning"
reportArgumentType = "warning"
reportAttributeAccessIssue = "warning"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E", 
    "F", 
    "I", 
    "B", 
    "C4",
    "UP", 
    "ARG", 
]
ignore = [
    "E501",
    "B008",
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.isort]
known-first-party = ["movie_viewer"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
